apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-backend
  template:
    metadata:
      labels:
        app: flight-backend
    spec:
      containers:
        - name: flight-backend
          image: flight-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/flightdb
            - name: SPRING_DATASOURCE_USERNAME
              value: flightuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: flightpass
---
apiVersion: v1
kind: Service
metadata:
  name: flight-backend
spec:
  selector:
    app: flight-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort 