apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-frontend
  template:
    metadata:
      labels:
        app: flight-frontend
    spec:
      containers:
        - name: flight-frontend
          image: flight-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_BASE
              value: "http://flight-backend:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: flight-frontend
spec:
  selector:
    app: flight-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort 